; PlatformIO Project Configuration
; https://docs.platformio.org/en/latest/boards/espressif32/esp32dev.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_protocol = espota
upload_port = http://192.168.1.203/
lib_deps =
    ncmreynolds/ld2410
    knolleary/PubSubClient
    bblanchon/ArduinoJson
    esp32async/ESPAsyncWebServer
    esp32async/AsyncTCP
    adafruit/DHT sensor library
